ToDo_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("to_do.urls", namespace="to_do")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

to_do/urls.py
from django.urls import path

from to_do.views import (
    TaskListView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    UpdateStatusTaskView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path('task/<int:pk>/status_update/', UpdateStatusTaskView.as_view(), name="update-status-task"),
]

app_name = "ToDo_list"

to_do/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField()
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["is_completed", "deadline"]

    def __str__(self) -> str:
        return self.content

to_do/forms.py
from django import forms
from to_do.models import Task


class TaskCreateForm(forms.ModelForm):
    deadline = forms.DateTimeField(widget=forms.DateTimeInput)

    class Meta:
        model = Task
        fields = "__all__"

to_do/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View
from to_do.forms import TaskCreateForm
from to_do.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    template_name = "to_do/index.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.values()
        return context


class TaskCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("to_do:index")
    form_class = TaskCreateForm


class TagListView(generic.ListView):
    model = Tag
    queryset = Tag.objects.prefetch_related("tasks__tags")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("to_do:tag-list")


class UpdateStatusTaskView(View):
    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_completed = not task.is_completed
        task.save()
        return redirect("to_do:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% block title %}<title>TODO List</title> {% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'to_do:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'to_do:tag-list' %}">Tags</a></li>
</ul>

templates/to_do/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO List
    <a href="{% url 'to_do:task-create' %}" class="btn btn-primary link-to-page float-right">Add task</a>
  </h1>

  {% if task_list %}
    <ul class="list-inline">
      {% for task in task_list  %}
        <li >
          <form method="post" action="{% url 'to_do:update-status-task' pk=task.id %}" style="display: inline;">
            {% csrf_token %}
            {% if task.is_completed %}
              <button type="submit" class="btn btn-secondary link-to-page float-right">Undo</button>
            {% else %}
              <button type="submit" class="btn btn-success link-to-page float-right">Complete</button>
            {% endif %}
          </form>
          <p>
            <strong>
              {{ task.content }}
              {% if task.is_completed == True %} <span class="text-success">Done</span>
              {% else %} <span class="text-danger">Not done</span>
              {% endif %}
            </strong>
          </p>
          <p>
            Created: {{ task.datetime }}
            {% if task.deadline %} <span class="text-info">Deadline: {{ task.deadline }}</span>
            {% endif %}
          </p>
          <h6 class="text-secondary">
            Tags: {% for tag in tags %} {{ tag.name }};{% endfor %}
          </h6>
        </li>
        <hr>
      {% endfor %}
    </ul>
  {% else %}
    <p>TODO list is empty, let us checkout and create a task.</p>
  {% endif %}
{% endblock %}

templates/to_do/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/to_do/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/to_do/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a class="btn btn-primary float-right" href="{% url 'to_do:tag-create' %}">Add</a>
  </h1>
  {% if tag_list %}
    <table class="table table-bordered">
      <tr>
        <th class="text-center">Name</th>
        <th class="text-center">Update</th>
        <th class="text-center">Delete</th>
      </tr>
      {% for tag in tag_list  %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a class="btn btn-secondary page-link" href="{% url 'to_do:tag-update' pk=tag.id %}">Update</a></td>
        <td><a class="btn btn-secondary page-link" href="{% url 'to_do:tag-delete' pk=tag.id  %}">Delete</a></td>
      </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>No Tags created. Add one if you want.</p>
{% endif %}
{% endblock %}

templates/to_do/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Add Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}